
import java.awt.BorderLayout;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juare
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1093, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static  Ventana panel1=new Ventana();
    public  static  boolean juevoEmpezado=true;
    private static HiloNave Hilo1=new HiloNave();
    private static HiloBalaJugador hiloBalaJugador=new HiloBalaJugador();
    public static HiloJugador hilojugador1=new HiloJugador();
    public static int velocidadAparicionNave=0;
   private static HiloGenerarNave hiloNaveAparecer=new HiloGenerarNave();
    private static HiloTiempo hiloTiempo=new HiloTiempo();
    private static HiloBalaNave hiloBalaNave=new HiloBalaNave();
    public static void main(String args[]) {
  
   
        //Jugador  jugador1=new Jugador(250,540);
        // Jugador  jugador2=new Jugador(750,540);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Panel panel=new Panel();
                panel.setBounds(300, 200, 1018, 600);
                panel.setResizable(false);
                panel.setVisible(true); 
                panel.setContentPane(panel1);
                //panel1.add(new Bala(100,300));
                hiloBalaNave.start(); 
                hiloBalaJugador.start();
                hilojugador1.start();
                Hilo1.start();
                hiloNaveAparecer.start();
                hiloTiempo.start();
            }
        });
    }
 
 
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
