import java.util.concurrent.ExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DOER
 */
public class CentroAcopio extends javax.swing.JFrame {

    /**
     * Creates new form CentroAcopio
     */
    private int nProductores=0;
    private int nConsumidores=0;
    private int nProductoresTotal=0;
    private int nConsumidoresTotal=0;
    ColaProveedorConsumidor cb = null;
    ExecutorService ejecutor;
    Thread hiloEjecucion = null;
    private int valCons;
    private int valProds;
    public CentroAcopio(ExecutorService ejecutor) {
        initComponents();
        this.ejecutor = ejecutor;
        this.valCons=50;
        this.valProds=50;
        this.lblConsPend.setText("Pendiente: 0");
        this.lblProdPend.setText("Pendiente: 0");
        this.lblConsSal.setText("Salieron: 0");
        this.lblProdSal.setText("Salieron: 0");
        this.jButton1.setVisible(false);
        this.start();
        this.setLocationRelativeTo(null);

    }
    private String generateStickMans(int i){
        String cabezas = "";
        String torsos = "";
        String piernas = "";
        for(int j=0;j<i;j++){
            cabezas+=" O     ";
            if(j%5==0){
                torsos+=" ";
            }
            torsos+=" -|-    ";
            piernas+=" /\\      ";
        }
        String content = cabezas+"\n"+torsos+"\n"+piernas;
        return content;
    }
    public void updateBodega(ColaProveedorConsumidor cb){
        this.txtBodega.setText("");
        String txtArea = "";
        
        for(int i=0; i<cb.getMax(); i++){
            txtArea+="[";
            if(cb.getCola()[i]!=0){
                txtArea+="O";
            }else{
                txtArea+="   ";
            }
            txtArea+="] ";
        }
        this.txtBodega.setText(txtArea);
    }
    
    public void gestionBodega(boolean agregar){
        if(agregar){
            for(int i=0;i<this.cb.getMax();i++){
                if(this.cb.getCola()[i]==0){
                    this.cb.getCola()[i]=1;
                    break;
                }
            }
        }else{
            for(int i=0;i<this.cb.getMax();i++){
                if(this.cb.getCola()[i]==0){
                    this.cb.getCola()[i-1]=0;
                    break;
                }
            }

        }
    }
    
    public void updateProductores(){
        this.lblProdSal.setText("Salieron: "+this.nProductoresTotal+"");
        this.lblProdPend.setText("Pendiente(s): "+this.nProductores+"");
        String txtProds = "";
        txtProds = this.generateStickMans(this.nProductores);
        this.txtAreaProd.setText("");
        this.txtAreaProd.setText(txtProds);
    }
    public void updateConsumidores(){
        this.lblConsSal.setText("Salieron: "+this.nConsumidoresTotal);
        this.lblConsPend.setText("Pendiente(s): "+this.nConsumidores+"");
        String txtCons = "";
        txtCons = this.generateStickMans(this.nConsumidores);
        this.txtAreaCons.setText("");
        this.txtAreaCons.setText(txtCons);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaProd = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaCons = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        lblProdSal = new javax.swing.JLabel();
        lblProdPend = new javax.swing.JLabel();
        lblConsSal = new javax.swing.JLabel();
        lblConsPend = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLlego = new javax.swing.JLabel();
        txtBodega = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlblConsumidoresPercent = new javax.swing.JLabel();
        jlblProductoresPercent = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblContador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Consumidores");

        jLabel2.setText("Productores");

        txtAreaProd.setColumns(20);
        txtAreaProd.setRows(5);
        jScrollPane1.setViewportView(txtAreaProd);

        txtAreaCons.setColumns(20);
        txtAreaCons.setRows(5);
        jScrollPane2.setViewportView(txtAreaCons);

        jLabel3.setText("Bodega");

        lblProdSal.setText("Salieron:");

        lblProdPend.setText("Pendientes:");

        lblConsSal.setText("Salieron:");

        lblConsPend.setText("Pendientes:");

        jLabel4.setText("Llegó: ");

        lblLlego.setText("Quien llegó?");

        txtBodega.setText("[X] [X] [X] [X] [X] [X] [X] [X] [X] [X] [X] [X] [X] [X] [X] [X] [X] [X] [X] [X] ");

        jLabel5.setText("Configuración");

        jSlider1.setBackground(new java.awt.Color(163, 184, 204));
        jSlider1.setForeground(new java.awt.Color(238, 238, 238));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel6.setText("Consumidores");

        jLabel7.setText("Productores");

        jlblConsumidoresPercent.setText("50%");

        jlblProductoresPercent.setText("50%");

        jButton1.setText("Setear y reiniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblContador.setText("Contador: 0/100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblConsPend)
                                .addGap(83, 83, 83)
                                .addComponent(lblConsSal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(lblLlego)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblProdPend)
                                .addGap(86, 86, 86)
                                .addComponent(lblProdSal))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jlblConsumidoresPercent))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jlblProductoresPercent))
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(34, 34, 34))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(txtBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblContador)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1)
                    .addComponent(lblContador))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblConsumidoresPercent)
                    .addComponent(jlblProductoresPercent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblLlego))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdSal)
                    .addComponent(lblProdPend)
                    .addComponent(lblConsSal)
                    .addComponent(lblConsPend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void start(){
        try{
//            this.hiloEjecucion.getThreadGroup().interrupt();
//            this.hiloEjecucion.getThreadGroup().destroy();
//            this.hiloEjecucion.interrupt();
//            this.ejecutor.shutdown();
//            this.ejecutor.shutdownNow();
//            while(this.ejecutor.awaitTermination(2, TimeUnit.SECONDS)){
//                System.out.println("Esperando a terminar");
//            }

        }catch(Exception e){
                System.out.println("4");

        }
        this.txtBodega.setText("loading...");
        this.nConsumidoresTotal=0;
        this.nConsumidores=0;
        this.nProductores=0;
        this.nProductoresTotal=0;
        this.txtAreaCons.setText("");
        this.txtAreaProd.setText("");
        this.lblConsPend.setText("Pendiente: 0");
        this.lblProdPend.setText("Pendiente: 0");
        this.lblConsSal.setText("Salieron: 0");
        this.lblProdSal.setText("Salieron: 0");
        this.hiloEjecucion= null;
        CentroAcopio that = this;
        this.hiloEjecucion = new Thread() {
            public void run() {
                try {
                    ColaProveedorConsumidor cola = new ColaProveedorConsumidor(20,that);
                    for (int i = 0; i < 100; i++) {
                        try {
                            try{
                                Thread.sleep(2000);                                
                            }catch(Exception e){
                                System.out.println("1");
                            }
                            ejecutor.execute( new HiloCola(cola,that.valProds,i));
                        } catch (Exception ex) {
                            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    ejecutor.shutdown();

                    try {
                        ejecutor.awaitTermination(Long.MAX_VALUE, TimeUnit.NANOSECONDS);
                        cola.print();
                    } catch (Exception e) {
                            System.out.println("2");
                    }
                }catch(Exception e) {
                                System.out.println("3");
                    
                }
            }  
        };
       
        this.hiloEjecucion.start();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        int valSlider =this.jSlider1.getValue();
        int valCons = 100-valSlider;
        this.jlblConsumidoresPercent.setText(valCons+"%");
        this.jlblProductoresPercent.setText(valSlider+"%");
        this.valCons = valCons;
        this.valProds = valSlider;
        
    }//GEN-LAST:event_jSlider1StateChanged

    public JLabel getLblLlego() {
        return lblLlego;
    }

    public void setLblLlego(JLabel lblLlego) {
        this.lblLlego = lblLlego;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel jlblConsumidoresPercent;
    private javax.swing.JLabel jlblProductoresPercent;
    private javax.swing.JLabel lblConsPend;
    private javax.swing.JLabel lblConsSal;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblLlego;
    private javax.swing.JLabel lblProdPend;
    private javax.swing.JLabel lblProdSal;
    private javax.swing.JTextArea txtAreaCons;
    private javax.swing.JTextArea txtAreaProd;
    private javax.swing.JTextField txtBodega;
    // End of variables declaration//GEN-END:variables

    public int getnProductores() {
        return nProductores;
    }

    public void setnProductores(int nProductores) {
        this.nProductores = nProductores;
    }

    public int getnConsumidores() {
        return nConsumidores;
    }

    public void setnConsumidores(int nConsumidores) {
        this.nConsumidores = nConsumidores;
    }

    public int getnProductoresTotal() {
        return nProductoresTotal;
    }

    public void setnProductoresTotal(int nProductoresTotal) {
        this.nProductoresTotal = nProductoresTotal;
    }

    public int getnConsumidoresTotal() {
        return nConsumidoresTotal;
    }

    public void setnConsumidoresTotal(int nConsumidoresTotal) {
        this.nConsumidoresTotal = nConsumidoresTotal;
    }

    public int getValCons() {
        return valCons;
    }

    public void setValCons(int valCons) {
        this.valCons = valCons;
    }

    public int getValProds() {
        return valProds;
    }

    public void setValProds(int valProds) {
        this.valProds = valProds;
    }

    public javax.swing.JLabel getLblContador() {
        return lblContador;
    }

    public void setLblContador(javax.swing.JLabel lblContador) {
        this.lblContador = lblContador;
    }
}
